name: fittrack15
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  fl_chart: ^0.66.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
